version: '2'
services:
  exercise-app:
    image: exercise
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://exercise-postgresql:5432/exercise
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  exercise-postgresql:
    extends:
      file: postgresql.yml
      service: exercise-postgresql
